#pragma once

/* USB Device descriptor parameter */
#define DEBOUNCE 5

/* Key matrix size */
#define MATRIX_ROWS 5
#define MATRIX_COLS 14

/* Matrix pins */
#define MATRIX_COL_PINS { A3, A4, A5, A6, A7, B0, B1, B12, B13, B14, B15, A8, A9, B3 }
#define MATRIX_ROW_PINS { B6, B5, B4, A15, B11 }

/* COL2ROW or ROW2COL */
#define DIODE_DIRECTION COL2ROW

/* Mechanical locking support */
#define LOCKING_SUPPORT_ENABLE
#define LOCKING_RESYNC_ENABLE

#define RGBLED_NUM 60
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8
#define RGBLIGHT_SLEEP
#define RGBLIGHT_LIMIT_VAL 180

// VIA 必须定义的宏
#define VIA_EEPROM_IS_USED
#ifndef RGB_MATRIX_ENABLE
#define RGB_MATRIX_ENABLE
#endif
   

/* RGB Matrix (WS2812) */

#define DRIVER_LED_TOTAL 60
#define RGB_MATRIX_LED_FLUSH_LIMIT 26
#define RGB_DISABLE_AFTER_TIMEOUT 0
#define RGB_DISABLE_WHEN_USB_SUSPENDED true
#define WS2812_DI_PIN B10
#define RGB_MATRIX_LED_COUNT 60
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 180
#define WS2812_SPI_MOSI_PAL_MODE 5
#define RGB_MATRIX_CENTER { 44, 20 }
